version: '2'
services:
    jhipstertravelmanager-app:
        image: jhipstertravelmanager
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://jhipstertravelmanager-mariadb:3306/jhipstertravelmanager
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstertravelmanager-mariadb:
        extends:
            file: mariadb.yml
            service: jhipstertravelmanager-mariadb
